export {default as Tabs} from "./tabs/tabs"
export {default as Admin} from "./admin/admin"
export {default as ObjectPage} from "./object/object"
export {default as HousePage} from "./house/house"
export {default as DebtPage} from "./debt/debt"
export {default as Table} from "./table/table"
